---
galaxy_info:
  author: "MTO79"
  role_name: "libvirt_install"
  description: "Install Libvirt and KVM packages on your system."
  license: "MIT"
  min_ansible_version: "2.13"
  standalone: true

  platforms:
    - name: EL
      versions:
        - "7"
        - "8"
        - "9"
    - name: Debian
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - all

  galaxy_tags:
    - "mto79"
    - "libvirt"
    - "kvm"
    - "virtualization"

dependencies: []

...
